export {
  NEUTRAL_PANEL_CLOSE_BUTTON as ROLEPLAY_POPOVER_CLOSE_BUTTON,
  NEUTRAL_PANEL_CLOSE_ICON_SIZE as ROLEPLAY_POPOVER_CLOSE_ICON_SIZE,
  NEUTRAL_PANEL_HEADER as ROLEPLAY_POPOVER_HEADER,
  NEUTRAL_PANEL_SCROLL_AREA as ROLEPLAY_POPOVER_SCROLL_AREA,
  NEUTRAL_PANEL_SHELL as ROLEPLAY_POPOVER_SHELL,
  NEUTRAL_PANEL_SUBTITLE as ROLEPLAY_POPOVER_SUBTITLE,
  NEUTRAL_PANEL_TITLE as ROLEPLAY_POPOVER_TITLE,
} from "../ui/neutral-surface-styles";
