// ──────────────────────────────────────────────
// Emoji search — shared by the picker grid and `:shortcode:` autocomplete.
//
// The generated catalog only carries official Unicode names ("red apple",
// "grinning face"), so a raw substring match misses everything users actually
// type: "happy", "thumbsup", "lol". Two layers fix that:
//   1. EMOJI_KEYWORDS — hand-written extras for the emoji people reach for most.
//   2. WORD_SYNONYMS — keyed on a *word* of the Unicode name, so one entry
//      covers every emoji containing that word (all 1,900+, not just curated).
// ──────────────────────────────────────────────
import { EMOJI_SEARCH_NAMES } from "./emoji-catalog.generated";

/** Word appearing in a Unicode emoji name → extra searchable terms. */
const WORD_SYNONYMS: Readonly<Record<string, string>> = {
  grinning: "happy smiley smile",
  smiling: "happy smiley smile",
  smile: "happy smiley",
  beaming: "happy smile",
  grin: "happy smile",
  laughing: "lol lmao haha funny",
  tears: "crying",
  joy: "lol haha funny",
  crying: "sad tears upset",
  frowning: "sad unhappy",
  pouting: "angry mad",
  angry: "mad rage",
  thumbs: "thumbsup thumbsdown",
  hand: "hands",
  heart: "love",
  kiss: "love",
  party: "celebrate celebration congrats",
  popper: "celebrate celebration congrats tada party",
  confetti: "celebrate celebration party",
  birthday: "cake celebrate",
  fire: "lit hot flame",
  hundred: "100 perfect",
  check: "tick done yes correct",
  sparkles: "star shiny glitter",
  poop: "poo shit turd",
  rocket: "launch space ship",
  computer: "pc laptop",
  telephone: "phone call",
  mobile: "phone cell",
  envelope: "mail email letter",
  memo: "note write pencil",
  bulb: "idea light",
  moneybag: "cash rich",
  banknote: "cash money bill",
  soccer: "football",
  american: "usa",
  automobile: "car",
  aeroplane: "airplane plane flight",
  airplane: "plane flight travel",
  luggage: "travel suitcase",
  beach: "travel holiday vacation sea",
  umbrella: "rain",
  cat: "kitten kitty",
  dog: "puppy doggo",
  face: "emoji",
  flag: "country",
  clock: "time oclock",
  keycap: "number digit",
  button: "sign symbol",
  sleeping: "tired zzz sleepy",
  vomiting: "sick puke ill",
  nauseated: "sick ill",
  skull: "dead death rip",
  ghost: "spooky halloween",
  alien: "ufo space",
  robot: "bot ai",
  clapping: "clap applause bravo",
  folded: "pray thanks please",
  waving: "wave hello hi bye",
  eyes: "look watch",
  brain: "smart think",
  muscle: "flex strong",
  warning: "caution careful alert",
  question: "help ask",
  loudly: "sob bawling",
};

/** Emoji → extra searchable keywords (lowercase). Curated for common emoji; the rest rely on their Unicode name. */
export const EMOJI_KEYWORDS: Readonly<Record<string, string>> = {
  "😀": "grinning face happy",
  "😃": "grinning big eyes happy",
  "😄": "grinning smiling happy",
  "😁": "beaming grin",
  "😆": "laughing squinting",
  "😅": "sweat grinning nervous",
  "🤣": "rofl rolling laughing",
  "😂": "joy tears laughing cry",
  "🙂": "slightly smiling",
  "😊": "blushing shy smiling",
  "😇": "innocent angel halo",
  "🥰": "love hearts smiling",
  "😍": "heart eyes love",
  "🤩": "star struck wow",
  "😘": "kiss blowing",
  "😗": "kissing",
  "😚": "kissing closed eyes",
  "😙": "kissing smiling",
  "🥲": "smiling tear sad",
  "😋": "yummy delicious tongue",
  "😛": "tongue out",
  "😜": "winking tongue playful",
  "🤪": "zany crazy wild",
  "😝": "squinting tongue",
  "🤑": "money face rich",
  "🤗": "hugging hug",
  "🤭": "giggling hand over mouth",
  "🫢": "open eyes hand over mouth",
  "🤫": "shushing quiet secret",
  "🤔": "thinking hmm",
  "🫡": "saluting salute",
  "🤐": "zipper mouth shut",
  "🤨": "raised eyebrow skeptical",
  "😐": "neutral face",
  "😑": "expressionless",
  "😶": "no mouth silent",
  "🫥": "dotted line invisible",
  "😏": "smirking smug",
  "😒": "unamused annoyed",
  "🙄": "eye roll whatever",
  "😬": "grimacing awkward",
  "🤥": "lying pinocchio",
  "😌": "relieved content peaceful",
  "😔": "sad pensive",
  "😪": "sleepy tired",
  "🤤": "drooling",
  "😴": "sleeping zzz",
  "😷": "mask sick",
  "🤒": "thermometer sick fever",
  "🤕": "bandage hurt injured",
  "🤢": "nauseous sick",
  "🤮": "vomiting puke",
  "🥴": "woozy drunk",
  "😵": "dizzy knocked out",
  "🤯": "exploding head mind blown",
  "🥳": "party celebrate birthday",
  "🥺": "pleading puppy eyes",
  "😢": "crying tear sad",
  "😭": "sobbing crying loud",
  "😤": "angry steam huffing",
  "😠": "angry face mad",
  "😡": "rage furious red",
  "🤬": "cursing swearing symbols",
  "😈": "devil smiling horns",
  "👿": "angry devil",
  "💀": "skull dead",
  "☠️": "skull crossbones death",
  "💩": "poop poo",
  "🤡": "clown",
  "👹": "ogre monster",
  "👺": "goblin tengu",
  "👻": "ghost boo",
  "👽": "alien ufo",
  "🤖": "robot",
  "😺": "cat grinning happy",
  "😸": "cat grinning smile",
  "😹": "cat joy tears",
  "😻": "cat heart eyes love",
  "😼": "cat smirk wry",
  "😽": "cat kissing",
  "🙀": "cat weary shocked",
  "😿": "cat crying sad",
  "😾": "cat pouting angry",
  "👋": "wave hi hello bye",
  "🤚": "raised back hand",
  "🖐️": "hand splayed",
  "✋": "raised hand stop high five",
  "🖖": "vulcan spock",
  "🫱": "rightward hand",
  "🫲": "leftward hand",
  "🫳": "palm down",
  "🫴": "palm up",
  "👌": "ok perfect",
  "🤌": "pinched fingers italian",
  "🤏": "pinching small tiny",
  "✌️": "peace victory",
  "🤞": "crossed fingers luck",
  "🫰": "index pointing heart",
  "🤟": "love you gesture",
  "🤘": "rock on metal horns",
  "🤙": "call me shaka",
  "👈": "pointing left",
  "👉": "pointing right",
  "👆": "pointing up",
  "🖕": "middle finger flip off",
  "👇": "pointing down",
  "☝️": "index pointing up",
  "🫵": "pointing at viewer",
  "👍": "thumbs up good yes",
  "👎": "thumbs down bad no",
  "✊": "raised fist",
  "👊": "fist bump punch",
  "🤛": "left fist",
  "🤜": "right fist",
  "👏": "clapping applause",
  "🙌": "raising hands celebrate",
  "🫶": "heart hands love",
  "👐": "open hands",
  "🤲": "palms up together",
  "🤝": "handshake deal",
  "🙏": "pray please thank you",
  "✍️": "writing hand",
  "💪": "muscle strong flexing",
  "🦾": "mechanical arm",
  "🦿": "mechanical leg",
  "🦵": "leg",
  "🦶": "foot",
  "👂": "ear listening",
  "🦻": "ear hearing aid",
  "👃": "nose smell",
  "🧠": "brain smart",
  "🫀": "anatomical heart",
  "🫁": "lungs",
  "🦷": "tooth",
  "🦴": "bone",
  "👀": "eyes looking",
  "👁️": "eye",
  "👅": "tongue",
  "👄": "mouth lips",
  "👶": "baby",
  "🧒": "child kid",
  "👦": "boy",
  "👧": "girl",
  "🧑": "person adult",
  "👱": "blonde",
  "👨": "man",
  "🧔": "bearded",
  "👩": "woman",
  "🧓": "older person",
  "👴": "old man grandpa",
  "👵": "old woman grandma",
  "💂": "guard",
  "👷": "construction worker",
  "🫅": "person crown king queen",
  "🤴": "prince",
  "👸": "princess",
  "👳": "turban",
  "🧕": "headscarf hijab",
  "🤵": "tuxedo groom",
  "👰": "bride veil wedding",
  "🤰": "pregnant",
  "🫃": "pregnant man",
  "🤱": "breastfeeding",
  "👼": "angel baby cherub",
  "🎅": "santa christmas",
  "🤶": "mrs claus christmas",
  "🦸": "superhero",
  "🦹": "supervillain",
  "🧙": "mage wizard",
  "🧚": "fairy",
  "🧛": "vampire",
  "🧜": "mermaid merman",
  "🧝": "elf",
  "🧞": "genie",
  "🧟": "zombie",
  "🧌": "troll",
  "💆": "massage",
  "💇": "haircut",
  "🚶": "walking",
  "🧍": "standing",
  "🧎": "kneeling",
  "🏃": "running",
  "💃": "dancer dancing woman",
  "🕺": "dancer dancing man",
  "🕴️": "hovering suit",
  "👯": "bunny ears",
  "🧖": "sauna steam",
  "🧗": "climbing",
  "🏌️": "golf",
  "🏄": "surfing",
  "🚣": "rowing",
  "🏊": "swimming",
  "⛹️": "basketball",
  "🏋️": "weightlifting gym",
  "🚴": "cycling biking",
  "🚵": "mountain biking",
  "🤸": "cartwheel",
  "🤼": "wrestling",
  "🤽": "water polo",
  "🤾": "handball",
  "🤺": "fencing",
  "⛷️": "skiing",
  "🏂": "snowboarding",
  "🏇": "horse racing",
  "❤️": "red heart love",
  "🧡": "orange heart",
  "💛": "yellow heart",
  "💚": "green heart",
  "💙": "blue heart",
  "💜": "purple heart",
  "🖤": "black heart",
  "🤍": "white heart",
  "🤎": "brown heart",
  "💔": "broken heart",
  "❤️‍🔥": "heart fire passion",
  "❤️‍🩹": "mending heart healing",
  "❣️": "exclamation heart",
  "💕": "two hearts",
  "💞": "revolving hearts",
  "💓": "beating heart",
  "💗": "growing heart",
  "💖": "sparkling heart",
  "💘": "heart arrow cupid",
  "💝": "heart ribbon gift",
  "💟": "heart decoration",
  "♥️": "heart suit card",
  "💑": "couple heart",
  "💏": "couple kiss",
  "👪": "family",
  "👨‍👩‍👦": "family man woman boy",
  "👨‍👩‍👧": "family man woman girl",
  "🌸": "cherry blossom flower pink",
  "💐": "bouquet flowers",
  "🌷": "tulip flower",
  "🌹": "rose flower red",
  "🥀": "wilted flower dead",
  "🌺": "hibiscus flower",
  "🌻": "sunflower",
  "🌼": "blossom flower",
  "🌱": "seedling sprout",
  "🪴": "potted plant",
  "🌲": "evergreen tree pine",
  "🌳": "deciduous tree",
  "🌴": "palm tree tropical beach holiday vacation",
  "🌵": "cactus desert",
  "🌾": "rice sheaf",
  "🌿": "herb leaf",
  "☘️": "shamrock clover",
  "🍀": "four leaf clover luck",
  "🍁": "maple leaf autumn fall",
  "🍂": "fallen leaf autumn",
  "🍃": "leaf wind",
  "🍄": "mushroom",
  "🪹": "empty nest",
  "🪺": "nest eggs",
  "🐾": "paw prints",
  "🐵": "monkey face",
  "🐒": "monkey",
  "🦍": "gorilla",
  "🦧": "orangutan",
  "🐶": "dog face puppy",
  "🐕": "dog",
  "🦮": "guide dog",
  "🐩": "poodle",
  "🐺": "wolf",
  "🦊": "fox",
  "🦝": "raccoon",
  "🐱": "cat face kitty",
  "🐈": "cat",
  "🦁": "lion",
  "🐯": "tiger face",
  "🐅": "tiger",
  "🐆": "leopard",
  "🐴": "horse face",
  "🫎": "moose",
  "🫏": "donkey",
  "🦄": "unicorn",
  "🦓": "zebra",
  "🐮": "cow face",
  "🐂": "ox",
  "🐃": "water buffalo",
  "🐄": "cow",
  "🐷": "pig face",
  "🐖": "pig",
  "🐗": "boar",
  "🐽": "pig nose",
  "🐏": "ram",
  "🐑": "sheep",
  "🐐": "goat",
  "🐪": "camel",
  "🐫": "two hump camel",
  "🦙": "llama",
  "🦒": "giraffe",
  "🐘": "elephant",
  "🦣": "mammoth",
  "🦏": "rhino",
  "🦛": "hippo",
  "🐭": "mouse face",
  "🐁": "mouse",
  "🐀": "rat",
  "🐹": "hamster",
  "🐰": "rabbit face bunny",
  "🐇": "rabbit",
  "🐿️": "chipmunk",
  "🦫": "beaver",
  "🦔": "hedgehog",
  "🦇": "bat",
  "🐻": "bear",
  "🐨": "koala",
  "🐼": "panda",
  "🦥": "sloth",
  "🦦": "otter",
  "🦨": "skunk",
  "🦘": "kangaroo",
  "🦡": "badger",
  "🍕": "pizza",
  "🍔": "hamburger burger",
  "🍟": "french fries",
  "🌭": "hot dog",
  "🥪": "sandwich",
  "🌮": "taco",
  "🌯": "burrito",
  "🍗": "chicken leg poultry",
  "🍖": "meat bone",
  "🥩": "steak cut meat",
  "🍣": "sushi",
  "🍱": "bento box",
  "🍜": "ramen noodles",
  "🍝": "spaghetti pasta",
  "🍲": "pot food stew",
  "🍛": "curry rice",
  "🍳": "egg cooking frying",
  "🥚": "egg",
  "🥞": "pancakes",
  "🧇": "waffle",
  "🧀": "cheese",
  "🥐": "croissant",
  "🍞": "bread loaf",
  "🥖": "baguette french bread",
  "🥯": "bagel",
  "🍩": "donut doughnut",
  "🍪": "cookie",
  "🎂": "birthday cake",
  "🍰": "shortcake cake",
  "🧁": "cupcake",
  "🍮": "custard flan",
  "🍭": "lollipop candy",
  "🍬": "candy sweet",
  "🍫": "chocolate bar",
  "🍿": "popcorn",
  "🍦": "ice cream soft serve",
  "🍧": "shaved ice",
  "🍨": "ice cream sundae",
  "☕": "coffee hot",
  "🍵": "tea green",
  "🧋": "bubble tea boba",
  "🥤": "cup straw soda",
  "🍺": "beer mug",
  "🍻": "clinking beers cheers",
  "🥂": "champagne toast wine",
  "🍷": "wine glass",
  "🍸": "cocktail martini",
  "🍹": "tropical drink",
  "🍾": "champagne bottle",
  "🍶": "sake",
  "🧊": "ice cube",
  "💻": "laptop computer",
  "📱": "phone mobile",
  "🖥️": "desktop computer monitor",
  "⌨️": "keyboard",
  "🖨️": "printer",
  "📷": "camera",
  "📸": "camera flash",
  "📹": "video camera",
  "🎥": "movie camera film",
  "📺": "television tv",
  "📻": "radio",
  "🎙️": "microphone studio mic",
  "⏰": "alarm clock",
  "🔮": "crystal ball fortune",
  "🧿": "nazar evil eye",
  "💎": "gem diamond jewel",
  "⚔️": "crossed swords",
  "🔫": "pistol gun water",
  "🏹": "bow arrow",
  "🛡️": "shield",
  "💡": "lightbulb idea",
  "🔦": "flashlight torch",
  "🕯️": "candle",
  "📚": "books stack",
  "📖": "open book reading",
  "📝": "memo writing note",
  "✏️": "pencil",
  "🔑": "key",
  "🗝️": "old key",
  "💯": "hundred perfect score",
  "🔥": "fire hot lit",
  "✨": "sparkles shiny",
  "⭐": "star favourite favorite",
  "🌈": "rainbow",
  "☀️": "sun sunny",
  "❄️": "snowflake cold winter",
  "🌊": "wave ocean water",
  "♠️": "spade card",
  "♦️": "diamond card",
  "♣️": "club card",
  "🎯": "bullseye target dart",
  "🎵": "music note",
  "🎶": "music notes",
  "✅": "check mark yes",
  "❌": "cross mark no wrong",
  "⭕": "circle",
  "❓": "question mark",
  "❗": "exclamation mark",
  "✔️": "check mark done",
  "🔴": "red circle",
  "🟠": "orange circle",
  "🟡": "yellow circle",
  "🟢": "green circle",
  "🔵": "blue circle",
  "🟣": "purple circle",
  "⚫": "black circle",
  "⚪": "white circle",
  "🟤": "brown circle",
  "💬": "speech bubble chat",
  "💭": "thought bubble",
  "💤": "sleeping zzz",
  "💥": "collision boom bang",
  "💢": "anger symbol",
  "💨": "dash wind fast",
  "🧪": "test tube lab laboratory science chemistry experiment",
  "⛱️": "beach parasol sunshade holiday vacation",
  "🏝️": "island beach tropical holiday vacation",
};

/** Split a name or query into lowercase alphanumeric words. */
function tokenize(value: string): string[] {
  return value
    .toLowerCase()
    .split(/[^a-z0-9]+/iu)
    .filter(Boolean);
}

const searchWordsCache = new Map<string, string[]>();

/** Deduplicated search words: Unicode name + curated keywords + synonyms for each word of the name. */
function emojiSearchWords(emoji: string): string[] {
  const cached = searchWordsCache.get(emoji);
  if (cached !== undefined) return cached;
  const words = tokenize(`${EMOJI_SEARCH_NAMES[emoji] ?? ""} ${EMOJI_KEYWORDS[emoji] ?? ""}`);
  const synonyms = words.flatMap((word) => tokenize(WORD_SYNONYMS[word] ?? ""));
  const unique = Array.from(new Set([...words, ...synonyms]));
  searchWordsCache.set(emoji, unique);
  return unique;
}

/** Unicode name + curated keywords + synonyms for each word of the name. */
export function emojiSearchText(emoji: string): string {
  return emojiSearchWords(emoji).join(" ");
}

/**
 * Every query word must prefix-match a word of the emoji's search text, so word
 * order does not matter ("face grinning") and "tick" no longer hits "chopsticks".
 * Pasting the emoji itself matches too.
 */
export function matchesEmojiQuery(query: string, emoji: string): boolean {
  if (emoji === query.trim()) return true;
  const queryWords = tokenize(query);
  if (queryWords.length === 0) return false;
  const words = emojiSearchWords(emoji);
  return queryWords.every((queryWord) => words.some((word) => word.startsWith(queryWord)));
}
