// ──────────────────────────────────────────────
// UI: Emoji Picker — lightweight popover
// ──────────────────────────────────────────────
import { useState, useRef, useEffect, useCallback, useLayoutEffect } from "react";
import { createPortal } from "react-dom";
import { cn } from "../../lib/utils";

/** Emoji → searchable keywords (lowercase). Only needs entries for emojis in CATEGORIES. */
const EMOJI_NAMES: Record<string, string> = {
  "😀": "grinning face happy",
  "😃": "grinning big eyes happy",
  "😄": "grinning smiling happy",
  "😁": "beaming grin",
  "😆": "laughing squinting",
  "😅": "sweat grinning nervous",
  "🤣": "rofl rolling laughing",
  "😂": "joy tears laughing cry",
  "🙂": "slightly smiling",
  "😊": "blushing shy smiling",
  "😇": "innocent angel halo",
  "🥰": "love hearts smiling",
  "😍": "heart eyes love",
  "🤩": "star struck wow",
  "😘": "kiss blowing",
  "😗": "kissing",
  "😚": "kissing closed eyes",
  "😙": "kissing smiling",
  "🥲": "smiling tear sad",
  "😋": "yummy delicious tongue",
  "😛": "tongue out",
  "😜": "winking tongue playful",
  "🤪": "zany crazy wild",
  "😝": "squinting tongue",
  "🤑": "money face rich",
  "🤗": "hugging hug",
  "🤭": "giggling hand over mouth",
  "🫢": "open eyes hand over mouth",
  "🤫": "shushing quiet secret",
  "🤔": "thinking hmm",
  "🫡": "saluting salute",
  "🤐": "zipper mouth shut",
  "🤨": "raised eyebrow skeptical",
  "😐": "neutral face",
  "😑": "expressionless",
  "😶": "no mouth silent",
  "🫥": "dotted line invisible",
  "😏": "smirking smug",
  "😒": "unamused annoyed",
  "🙄": "eye roll whatever",
  "😬": "grimacing awkward",
  "🤥": "lying pinocchio",
  "😌": "relieved content peaceful",
  "😔": "sad pensive",
  "😪": "sleepy tired",
  "🤤": "drooling",
  "😴": "sleeping zzz",
  "😷": "mask sick",
  "🤒": "thermometer sick fever",
  "🤕": "bandage hurt injured",
  "🤢": "nauseous sick",
  "🤮": "vomiting puke",
  "🥴": "woozy drunk",
  "😵": "dizzy knocked out",
  "🤯": "exploding head mind blown",
  "🥳": "party celebrate birthday",
  "🥺": "pleading puppy eyes",
  "😢": "crying tear sad",
  "😭": "sobbing crying loud",
  "😤": "angry steam huffing",
  "😠": "angry face mad",
  "😡": "rage furious red",
  "🤬": "cursing swearing symbols",
  "😈": "devil smiling horns",
  "👿": "angry devil",
  "💀": "skull dead",
  "☠️": "skull crossbones death",
  "💩": "poop poo",
  "🤡": "clown",
  "👹": "ogre monster",
  "👺": "goblin tengu",
  "👻": "ghost boo",
  "👽": "alien ufo",
  "🤖": "robot",
  "😺": "cat grinning happy",
  "😸": "cat grinning smile",
  "😹": "cat joy tears",
  "😻": "cat heart eyes love",
  "😼": "cat smirk wry",
  "😽": "cat kissing",
  "🙀": "cat weary shocked",
  "😿": "cat crying sad",
  "😾": "cat pouting angry",
  "👋": "wave hi hello bye",
  "🤚": "raised back hand",
  "🖐️": "hand splayed",
  "✋": "raised hand stop high five",
  "🖖": "vulcan spock",
  "🫱": "rightward hand",
  "🫲": "leftward hand",
  "🫳": "palm down",
  "🫴": "palm up",
  "👌": "ok perfect",
  "🤌": "pinched fingers italian",
  "🤏": "pinching small tiny",
  "✌️": "peace victory",
  "🤞": "crossed fingers luck",
  "🫰": "index pointing heart",
  "🤟": "love you gesture",
  "🤘": "rock on metal horns",
  "🤙": "call me shaka",
  "👈": "pointing left",
  "👉": "pointing right",
  "👆": "pointing up",
  "🖕": "middle finger flip off",
  "👇": "pointing down",
  "☝️": "index pointing up",
  "🫵": "pointing at viewer",
  "👍": "thumbs up good yes",
  "👎": "thumbs down bad no",
  "✊": "raised fist",
  "👊": "fist bump punch",
  "🤛": "left fist",
  "🤜": "right fist",
  "👏": "clapping applause",
  "🙌": "raising hands celebrate",
  "🫶": "heart hands love",
  "👐": "open hands",
  "🤲": "palms up together",
  "🤝": "handshake deal",
  "🙏": "pray please thank you",
  "✍️": "writing hand",
  "💪": "muscle strong flexing",
  "🦾": "mechanical arm",
  "🦿": "mechanical leg",
  "🦵": "leg",
  "🦶": "foot",
  "👂": "ear listening",
  "🦻": "ear hearing aid",
  "👃": "nose smell",
  "🧠": "brain smart",
  "🫀": "anatomical heart",
  "🫁": "lungs",
  "🦷": "tooth",
  "🦴": "bone",
  "👀": "eyes looking",
  "👁️": "eye",
  "👅": "tongue",
  "👄": "mouth lips",
  "👶": "baby",
  "🧒": "child kid",
  "👦": "boy",
  "👧": "girl",
  "🧑": "person adult",
  "👱": "blonde",
  "👨": "man",
  "🧔": "bearded",
  "👩": "woman",
  "🧓": "older person",
  "👴": "old man grandpa",
  "👵": "old woman grandma",
  "💂": "guard",
  "👷": "construction worker",
  "🫅": "person crown king queen",
  "🤴": "prince",
  "👸": "princess",
  "👳": "turban",
  "🧕": "headscarf hijab",
  "🤵": "tuxedo groom",
  "👰": "bride veil wedding",
  "🤰": "pregnant",
  "🫃": "pregnant man",
  "🤱": "breastfeeding",
  "👼": "angel baby cherub",
  "🎅": "santa christmas",
  "🤶": "mrs claus christmas",
  "🦸": "superhero",
  "🦹": "supervillain",
  "🧙": "mage wizard",
  "🧚": "fairy",
  "🧛": "vampire",
  "🧜": "mermaid merman",
  "🧝": "elf",
  "🧞": "genie",
  "🧟": "zombie",
  "🧌": "troll",
  "💆": "massage",
  "💇": "haircut",
  "🚶": "walking",
  "🧍": "standing",
  "🧎": "kneeling",
  "🏃": "running",
  "💃": "dancer dancing woman",
  "🕺": "dancer dancing man",
  "🕴️": "hovering suit",
  "👯": "bunny ears",
  "🧖": "sauna steam",
  "🧗": "climbing",
  "🏌️": "golf",
  "🏄": "surfing",
  "🚣": "rowing",
  "🏊": "swimming",
  "⛹️": "basketball",
  "🏋️": "weightlifting gym",
  "🚴": "cycling biking",
  "🚵": "mountain biking",
  "🤸": "cartwheel",
  "🤼": "wrestling",
  "🤽": "water polo",
  "🤾": "handball",
  "🤺": "fencing",
  "⛷️": "skiing",
  "🏂": "snowboarding",
  "🏇": "horse racing",
  "❤️": "red heart love",
  "🧡": "orange heart",
  "💛": "yellow heart",
  "💚": "green heart",
  "💙": "blue heart",
  "💜": "purple heart",
  "🖤": "black heart",
  "🤍": "white heart",
  "🤎": "brown heart",
  "💔": "broken heart",
  "❤️‍🔥": "heart fire passion",
  "❤️‍🩹": "mending heart healing",
  "❣️": "exclamation heart",
  "💕": "two hearts",
  "💞": "revolving hearts",
  "💓": "beating heart",
  "💗": "growing heart",
  "💖": "sparkling heart",
  "💘": "heart arrow cupid",
  "💝": "heart ribbon gift",
  "💟": "heart decoration",
  "♥️": "heart suit card",
  "💑": "couple heart",
  "💏": "couple kiss",
  "👪": "family",
  "👨‍👩‍👦": "family man woman boy",
  "👨‍👩‍👧": "family man woman girl",
  "🌸": "cherry blossom flower pink",
  "💐": "bouquet flowers",
  "🌷": "tulip flower",
  "🌹": "rose flower red",
  "🥀": "wilted flower dead",
  "🌺": "hibiscus flower",
  "🌻": "sunflower",
  "🌼": "blossom flower",
  "🌱": "seedling sprout",
  "🪴": "potted plant",
  "🌲": "evergreen tree pine",
  "🌳": "deciduous tree",
  "🌴": "palm tree tropical",
  "🌵": "cactus desert",
  "🌾": "rice sheaf",
  "🌿": "herb leaf",
  "☘️": "shamrock clover",
  "🍀": "four leaf clover luck",
  "🍁": "maple leaf autumn fall",
  "🍂": "fallen leaf autumn",
  "🍃": "leaf wind",
  "🍄": "mushroom",
  "🪹": "empty nest",
  "🪺": "nest eggs",
  "🐾": "paw prints",
  "🐵": "monkey face",
  "🐒": "monkey",
  "🦍": "gorilla",
  "🦧": "orangutan",
  "🐶": "dog face puppy",
  "🐕": "dog",
  "🦮": "guide dog",
  "🐩": "poodle",
  "🐺": "wolf",
  "🦊": "fox",
  "🦝": "raccoon",
  "🐱": "cat face kitty",
  "🐈": "cat",
  "🦁": "lion",
  "🐯": "tiger face",
  "🐅": "tiger",
  "🐆": "leopard",
  "🐴": "horse face",
  "🫎": "moose",
  "🫏": "donkey",
  "🦄": "unicorn",
  "🦓": "zebra",
  "🐮": "cow face",
  "🐂": "ox",
  "🐃": "water buffalo",
  "🐄": "cow",
  "🐷": "pig face",
  "🐖": "pig",
  "🐗": "boar",
  "🐽": "pig nose",
  "🐏": "ram",
  "🐑": "sheep",
  "🐐": "goat",
  "🐪": "camel",
  "🐫": "two hump camel",
  "🦙": "llama",
  "🦒": "giraffe",
  "🐘": "elephant",
  "🦣": "mammoth",
  "🦏": "rhino",
  "🦛": "hippo",
  "🐭": "mouse face",
  "🐁": "mouse",
  "🐀": "rat",
  "🐹": "hamster",
  "🐰": "rabbit face bunny",
  "🐇": "rabbit",
  "🐿️": "chipmunk",
  "🦫": "beaver",
  "🦔": "hedgehog",
  "🦇": "bat",
  "🐻": "bear",
  "🐨": "koala",
  "🐼": "panda",
  "🦥": "sloth",
  "🦦": "otter",
  "🦨": "skunk",
  "🦘": "kangaroo",
  "🦡": "badger",
  "🍕": "pizza",
  "🍔": "hamburger burger",
  "🍟": "french fries",
  "🌭": "hot dog",
  "🥪": "sandwich",
  "🌮": "taco",
  "🌯": "burrito",
  "🍗": "chicken leg poultry",
  "🍖": "meat bone",
  "🥩": "steak cut meat",
  "🍣": "sushi",
  "🍱": "bento box",
  "🍜": "ramen noodles",
  "🍝": "spaghetti pasta",
  "🍲": "pot food stew",
  "🍛": "curry rice",
  "🍳": "egg cooking frying",
  "🥚": "egg",
  "🥞": "pancakes",
  "🧇": "waffle",
  "🧀": "cheese",
  "🥐": "croissant",
  "🍞": "bread loaf",
  "🥖": "baguette french bread",
  "🥯": "bagel",
  "🍩": "donut doughnut",
  "🍪": "cookie",
  "🎂": "birthday cake",
  "🍰": "shortcake cake",
  "🧁": "cupcake",
  "🍮": "custard flan",
  "🍭": "lollipop candy",
  "🍬": "candy sweet",
  "🍫": "chocolate bar",
  "🍿": "popcorn",
  "🍦": "ice cream soft serve",
  "🍧": "shaved ice",
  "🍨": "ice cream sundae",
  "☕": "coffee hot",
  "🍵": "tea green",
  "🧋": "bubble tea boba",
  "🥤": "cup straw soda",
  "🍺": "beer mug",
  "🍻": "clinking beers cheers",
  "🥂": "champagne toast wine",
  "🍷": "wine glass",
  "🍸": "cocktail martini",
  "🍹": "tropical drink",
  "🍾": "champagne bottle",
  "🍶": "sake",
  "🧊": "ice cube",
  "💻": "laptop computer",
  "📱": "phone mobile",
  "🖥️": "desktop computer monitor",
  "⌨️": "keyboard",
  "🖨️": "printer",
  "📷": "camera",
  "📸": "camera flash",
  "📹": "video camera",
  "🎥": "movie camera film",
  "📺": "television tv",
  "📻": "radio",
  "🎙️": "microphone studio mic",
  "⏰": "alarm clock",
  "🔮": "crystal ball fortune",
  "🧿": "nazar evil eye",
  "💎": "gem diamond jewel",
  "⚔️": "crossed swords",
  "🔫": "pistol gun water",
  "🏹": "bow arrow",
  "🛡️": "shield",
  "💡": "lightbulb idea",
  "🔦": "flashlight torch",
  "🕯️": "candle",
  "📚": "books stack",
  "📖": "open book reading",
  "📝": "memo writing note",
  "✏️": "pencil",
  "🔑": "key",
  "🗝️": "old key",
  "💯": "hundred perfect score",
  "🔥": "fire hot lit",
  "✨": "sparkles shiny",
  "🌈": "rainbow",
  "☀️": "sun sunny",
  "❄️": "snowflake cold winter",
  "🌊": "wave ocean water",
  "♠️": "spade card",
  "♦️": "diamond card",
  "♣️": "club card",
  "🎯": "bullseye target dart",
  "🎵": "music note",
  "🎶": "music notes",
  "✅": "check mark yes",
  "❌": "cross mark no wrong",
  "⭕": "circle",
  "❓": "question mark",
  "❗": "exclamation mark",
  "✔️": "check mark done",
  "🔴": "red circle",
  "🟠": "orange circle",
  "🟡": "yellow circle",
  "🟢": "green circle",
  "🔵": "blue circle",
  "🟣": "purple circle",
  "⚫": "black circle",
  "⚪": "white circle",
  "🟤": "brown circle",
  "💬": "speech bubble chat",
  "💭": "thought bubble",
  "💤": "sleeping zzz",
  "💥": "collision boom bang",
  "💢": "anger symbol",
  "💨": "dash wind fast",
};

const CATEGORIES = [
  {
    label: "Smileys",
    icon: "😀",
    emojis: [
      "😀",
      "😃",
      "😄",
      "😁",
      "😆",
      "😅",
      "🤣",
      "😂",
      "🙂",
      "😊",
      "😇",
      "🥰",
      "😍",
      "🤩",
      "😘",
      "😗",
      "😚",
      "😙",
      "🥲",
      "😋",
      "😛",
      "😜",
      "🤪",
      "😝",
      "🤑",
      "🤗",
      "🤭",
      "🫢",
      "🤫",
      "🤔",
      "🫡",
      "🤐",
      "🤨",
      "😐",
      "😑",
      "😶",
      "🫥",
      "😏",
      "😒",
      "🙄",
      "😬",
      "🤥",
      "😌",
      "😔",
      "😪",
      "🤤",
      "😴",
      "😷",
      "🤒",
      "🤕",
      "🤢",
      "🤮",
      "🥴",
      "😵",
      "🤯",
      "🥳",
      "🥺",
      "😢",
      "😭",
      "😤",
      "😠",
      "😡",
      "🤬",
      "😈",
      "👿",
      "💀",
      "☠️",
      "💩",
      "🤡",
      "👹",
      "👺",
      "👻",
      "👽",
      "🤖",
      "😺",
      "😸",
      "😹",
      "😻",
      "😼",
      "😽",
      "🙀",
      "😿",
      "😾",
    ],
  },
  {
    label: "Gestures",
    icon: "👋",
    emojis: [
      "👋",
      "🤚",
      "🖐️",
      "✋",
      "🖖",
      "🫱",
      "🫲",
      "🫳",
      "🫴",
      "👌",
      "🤌",
      "🤏",
      "✌️",
      "🤞",
      "🫰",
      "🤟",
      "🤘",
      "🤙",
      "👈",
      "👉",
      "👆",
      "🖕",
      "👇",
      "☝️",
      "🫵",
      "👍",
      "👎",
      "✊",
      "👊",
      "🤛",
      "🤜",
      "👏",
      "🙌",
      "🫶",
      "👐",
      "🤲",
      "🤝",
      "🙏",
      "✍️",
      "💪",
      "🦾",
      "🦿",
      "🦵",
      "🦶",
      "👂",
      "🦻",
      "👃",
      "🧠",
      "🫀",
      "🫁",
      "🦷",
      "🦴",
      "👀",
      "👁️",
      "👅",
      "👄",
    ],
  },
  {
    label: "People",
    icon: "👤",
    emojis: [
      "👶",
      "🧒",
      "👦",
      "👧",
      "🧑",
      "👱",
      "👨",
      "🧔",
      "👩",
      "🧓",
      "👴",
      "👵",
      "💂",
      "👷",
      "🫅",
      "🤴",
      "👸",
      "👳",
      "🧕",
      "🤵",
      "👰",
      "🤰",
      "🫃",
      "🤱",
      "👼",
      "🎅",
      "🤶",
      "🦸",
      "🦹",
      "🧙",
      "🧚",
      "🧛",
      "🧜",
      "🧝",
      "🧞",
      "🧟",
      "🧌",
      "💆",
      "💇",
      "🚶",
      "🧍",
      "🧎",
      "🏃",
      "💃",
      "🕺",
      "🕴️",
      "👯",
      "🧖",
      "🧗",
      "🏌️",
      "🏄",
      "🚣",
      "🏊",
      "⛹️",
      "🏋️",
      "🚴",
      "🚵",
      "🤸",
      "🤼",
      "🤽",
      "🤾",
      "🤺",
      "⛷️",
      "🏂",
      "🏇",
    ],
  },
  {
    label: "Hearts",
    icon: "❤️",
    emojis: [
      "❤️",
      "🧡",
      "💛",
      "💚",
      "💙",
      "💜",
      "🖤",
      "🤍",
      "🤎",
      "💔",
      "❤️‍🔥",
      "❤️‍🩹",
      "❣️",
      "💕",
      "💞",
      "💓",
      "💗",
      "💖",
      "💘",
      "💝",
      "💟",
      "♥️",
      "🫶",
      "💑",
      "💏",
      "👪",
      "👨‍👩‍👦",
      "👨‍👩‍👧",
    ],
  },
  {
    label: "Nature",
    icon: "🌸",
    emojis: [
      "🌸",
      "💐",
      "🌷",
      "🌹",
      "🥀",
      "🌺",
      "🌻",
      "🌼",
      "🌱",
      "🪴",
      "🌲",
      "🌳",
      "🌴",
      "🌵",
      "🌾",
      "🌿",
      "☘️",
      "🍀",
      "🍁",
      "🍂",
      "🍃",
      "🍄",
      "🪹",
      "🪺",
      "🐾",
      "🐵",
      "🐒",
      "🦍",
      "🦧",
      "🐶",
      "🐕",
      "🦮",
      "🐩",
      "🐺",
      "🦊",
      "🦝",
      "🐱",
      "🐈",
      "🦁",
      "🐯",
      "🐅",
      "🐆",
      "🐴",
      "🫎",
      "🫏",
      "🦄",
      "🦓",
      "🐮",
      "🐂",
      "🐃",
      "🐄",
      "🐷",
      "🐖",
      "🐗",
      "🐽",
      "🐏",
      "🐑",
      "🐐",
      "🐪",
      "🐫",
      "🦙",
      "🦒",
      "🐘",
      "🦣",
      "🦏",
      "🦛",
      "🐭",
      "🐁",
      "🐀",
      "🐹",
      "🐰",
      "🐇",
      "🐿️",
      "🦫",
      "🦔",
      "🦇",
      "🐻",
      "🐨",
      "🐼",
      "🦥",
      "🦦",
      "🦨",
      "🦘",
      "🦡",
      "🐾",
    ],
  },
  {
    label: "Food",
    icon: "🍕",
    emojis: [
      "🍏",
      "🍎",
      "🍐",
      "🍊",
      "🍋",
      "🍌",
      "🍉",
      "🍇",
      "🍓",
      "🫐",
      "🍈",
      "🍒",
      "🍑",
      "🥭",
      "🍍",
      "🥥",
      "🥝",
      "🍅",
      "🍆",
      "🥑",
      "🥦",
      "🥬",
      "🥒",
      "🌶️",
      "🫑",
      "🌽",
      "🥕",
      "🫒",
      "🧄",
      "🧅",
      "🥔",
      "🍠",
      "🫘",
      "🥐",
      "🥯",
      "🍞",
      "🥖",
      "🥨",
      "🧀",
      "🥚",
      "🍳",
      "🧈",
      "🥞",
      "🧇",
      "🥓",
      "🥩",
      "🍗",
      "🍖",
      "🌭",
      "🍔",
      "🍟",
      "🍕",
      "🫓",
      "🥪",
      "🥙",
      "🧆",
      "🌮",
      "🌯",
      "🫔",
      "🥗",
      "🥘",
      "🫕",
      "🥫",
      "🍝",
      "🍜",
      "🍲",
      "🍛",
      "🍣",
      "🍱",
      "🥟",
      "🦪",
      "🍤",
      "🍙",
      "🍚",
      "🍘",
      "🍥",
      "🥠",
      "🥮",
      "🍢",
      "🍡",
      "🍧",
      "🍨",
      "🍦",
      "🥧",
      "🧁",
      "🍰",
      "🎂",
      "🍮",
      "🍭",
      "🍬",
      "🍫",
      "🍿",
      "🧂",
      "🥤",
      "🧋",
      "🫙",
      "🧃",
      "🥛",
      "🍼",
      "☕",
      "🫖",
      "🍵",
      "🍶",
      "🍺",
      "🍻",
      "🥂",
      "🍷",
      "🫗",
      "🥃",
      "🍸",
      "🍹",
      "🍾",
      "🧊",
    ],
  },
  {
    label: "Objects",
    icon: "💡",
    emojis: [
      "⌚",
      "📱",
      "💻",
      "⌨️",
      "🖥️",
      "🖨️",
      "🖱️",
      "🖲️",
      "💽",
      "💾",
      "💿",
      "📀",
      "🧮",
      "📷",
      "📸",
      "📹",
      "🎥",
      "📞",
      "☎️",
      "📺",
      "📻",
      "🎙️",
      "⏱️",
      "⏲️",
      "⏰",
      "🕰️",
      "🔮",
      "🧿",
      "🪬",
      "💎",
      "⚖️",
      "🔧",
      "🔨",
      "⚒️",
      "🛠️",
      "🗡️",
      "⚔️",
      "🔫",
      "🏹",
      "🛡️",
      "🪃",
      "🪚",
      "🔩",
      "🪝",
      "🧲",
      "💡",
      "🔦",
      "🕯️",
      "📔",
      "📕",
      "📖",
      "📗",
      "📘",
      "📙",
      "📚",
      "📓",
      "📒",
      "📃",
      "📜",
      "📄",
      "📰",
      "🗞️",
      "✂️",
      "📌",
      "📍",
      "🖊️",
      "🖋️",
      "✒️",
      "📝",
      "✏️",
      "🔎",
      "🔏",
      "🔐",
      "🔑",
      "🗝️",
    ],
  },
  {
    label: "Symbols",
    icon: "💯",
    emojis: [
      "❤️",
      "💯",
      "💢",
      "💥",
      "💫",
      "💦",
      "💨",
      "🕳️",
      "💣",
      "💬",
      "👁️‍🗨️",
      "🗨️",
      "🗯️",
      "💭",
      "💤",
      "🔥",
      "✨",
      "🌟",
      "💫",
      "⭐",
      "🌈",
      "☀️",
      "🌤️",
      "⛅",
      "🌥️",
      "☁️",
      "🌦️",
      "🌧️",
      "⛈️",
      "🌩️",
      "🌪️",
      "🌫️",
      "🌬️",
      "❄️",
      "☃️",
      "⛄",
      "💧",
      "💦",
      "🌊",
      "♠️",
      "♥️",
      "♦️",
      "♣️",
      "🎯",
      "🎵",
      "🎶",
      "🔴",
      "🟠",
      "🟡",
      "🟢",
      "🔵",
      "🟣",
      "⚫",
      "⚪",
      "🟤",
      "✅",
      "❌",
      "⭕",
      "❓",
      "❗",
      "‼️",
      "⁉️",
      "0️⃣",
      "1️⃣",
      "2️⃣",
      "3️⃣",
      "4️⃣",
      "5️⃣",
      "6️⃣",
      "7️⃣",
      "8️⃣",
      "9️⃣",
      "🔟",
      "🔢",
      "#️⃣",
      "*️⃣",
      "🔤",
      "🔡",
      "🔠",
      "🔣",
      "🅰️",
      "🅱️",
      "🆎",
      "🆑",
      "🆒",
      "🆓",
      "🆔",
      "🆕",
      "🆖",
      "🆗",
      "🆘",
      "🆙",
      "🆚",
      "🈁",
      "🈂️",
      "㊗️",
      "㊙️",
      "🈲",
      "🈳",
      "🈴",
      "🈵",
      "🈶",
      "🈷️",
      "🈸",
      "🈹",
      "🈺",
      "🉐",
      "🉑",
      "✔️",
      "☑️",
      "⬛",
      "⬜",
      "◼️",
      "◻️",
      "◾",
      "◽",
      "▪️",
      "▫️",
      "🔶",
      "🔷",
      "🔸",
      "🔹",
      "🔺",
      "🔻",
    ],
  },
] as const;

interface EmojiPickerProps {
  open: boolean;
  onClose: () => void;
  onSelect: (emoji: string) => void;
  /** Position anchor — the button that triggered it (horizontal alignment) */
  anchorRef?: React.RefObject<HTMLElement | null>;
  /** Container (e.g. input bar) whose top edge determines vertical placement */
  containerRef?: React.RefObject<HTMLElement | null>;
  /** Optional extra tab (e.g. custom emojis) shown after the standard categories. */
  customTab?: { icon: React.ReactNode; label?: string; render: (query: string) => React.ReactNode };
  /** Render inline to fill a parent (no portal/positioning) — e.g. inside the mobile composer sheet. */
  embedded?: boolean;
}

export function EmojiPicker({ open, onClose, onSelect, anchorRef, containerRef, customTab, embedded }: EmojiPickerProps) {
  const [search, setSearch] = useState("");
  const [activeCategory, setActiveCategory] = useState<number | "custom">(0);
  const panelRef = useRef<HTMLDivElement>(null);

  // Close on outside click
  useEffect(() => {
    if (!open) return;
    const handler = (e: MouseEvent) => {
      if (
        panelRef.current &&
        !panelRef.current.contains(e.target as Node) &&
        anchorRef?.current &&
        !anchorRef.current.contains(e.target as Node)
      ) {
        onClose();
      }
    };
    document.addEventListener("mousedown", handler);
    return () => document.removeEventListener("mousedown", handler);
  }, [open, onClose, anchorRef]);

  // Close on Escape
  useEffect(() => {
    if (!open) return;
    const handler = (e: KeyboardEvent) => {
      if (e.key === "Escape") onClose();
    };
    document.addEventListener("keydown", handler);
    return () => document.removeEventListener("keydown", handler);
  }, [open, onClose]);

  // Position state for portal
  const [pos, setPos] = useState<{
    top?: number;
    bottom?: number;
    right?: number;
    left?: number;
    maxHeight?: number;
  }>({});

  useLayoutEffect(() => {
    if (!open || !anchorRef?.current) return;
    const btnRect = anchorRef.current.getBoundingClientRect();
    const pad = 8;
    const pickerWidth = 336; // 21rem
    const pickerHeight = 352; // 22rem
    const vw = window.innerWidth;
    const vh = window.innerHeight;

    // Composer mode (anchored to an input bar): pin the bottom edge above the bar's
    // top and grow upward. The bar sits at the bottom of the screen, so this fits.
    if (containerRef?.current) {
      const barRect = containerRef.current.getBoundingClientRect();
      const bottom = vh - barRect.top + pad;
      if (vw < 480) {
        // Center horizontally on mobile
        const left = Math.max(pad, (vw - Math.min(pickerWidth, vw - 2 * pad)) / 2);
        setPos({ bottom, left });
      } else {
        const right = Math.max(pad, vw - btnRect.right);
        setPos({ bottom, right });
      }
      return;
    }

    // Anchored mode (e.g. a message's reaction button, which can sit anywhere on
    // screen): open BELOW the anchor; flip above only when there isn't room below;
    // and clamp to the viewport so the panel never crosses an edge.
    const maxHeight = Math.min(pickerHeight, vh - 2 * pad);
    const spaceBelow = vh - btnRect.bottom;
    const openBelow = spaceBelow >= maxHeight + pad || spaceBelow >= btnRect.top;
    let top = openBelow ? btnRect.bottom + pad : btnRect.top - pad - maxHeight;
    top = Math.max(pad, Math.min(top, vh - maxHeight - pad));
    // Align the panel's right edge to the button, then clamp into view.
    let left = btnRect.right - pickerWidth;
    left = Math.max(pad, Math.min(left, vw - pickerWidth - pad));
    setPos({ top, left, maxHeight });
  }, [open, anchorRef, containerRef]);

  const handleSelect = useCallback(
    (emoji: string) => {
      onSelect(emoji);
    },
    [onSelect],
  );

  if (!open) return null;

  // Filter emojis by search
  const filteredCategories = search.trim()
    ? (() => {
        const q = search.trim().toLowerCase();
        return CATEGORIES.map((cat) => ({
          ...cat,
          emojis: cat.emojis.filter((emoji) => {
            const names = EMOJI_NAMES[emoji];
            return names ? names.includes(q) : false;
          }),
        })).filter((cat) => cat.emojis.length > 0);
      })()
    : CATEGORIES;

  const content = (
    <>
      {/* Search — filters the active standard category, or the custom tab's emojis */}
      <div className="border-b border-foreground/10 px-3 py-2">
        <input
          type="text"
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          placeholder="Buscar emojis..."
          className="w-full rounded-md bg-foreground/5 px-2.5 py-1.5 text-xs outline-none ring-1 ring-foreground/10 transition-shadow placeholder:text-foreground/35 focus:ring-foreground/20"
          autoFocus={!embedded}
        />
      </div>

      {/* Category tabs */}
      <div className="flex items-center gap-0.5 border-b border-foreground/10 px-2 py-1">
        {CATEGORIES.map((cat, i) => (
          <button
            key={cat.label}
            type="button"
            onClick={() => setActiveCategory(i)}
            className={cn(
              "rounded-md p-1.5 text-sm transition-colors",
              activeCategory === i
                ? "bg-foreground/10 text-foreground/80 ring-1 ring-foreground/15"
                : "text-foreground/45 hover:bg-foreground/10 hover:text-foreground/70",
            )}
            title={cat.label}
          >
            {cat.icon}
          </button>
        ))}
        {customTab && (
          <button
            type="button"
            onClick={() => setActiveCategory("custom")}
            className={cn(
              "ml-auto flex items-center rounded-md p-1.5 text-sm transition-colors",
              activeCategory === "custom"
                ? "bg-foreground/10 text-foreground/80 ring-1 ring-foreground/15"
                : "text-foreground/45 hover:bg-foreground/10 hover:text-foreground/70",
            )}
            title={customTab.label ?? "Custom"}
          >
            {customTab.icon}
          </button>
        )}
      </div>

      {/* Emoji grid (or the custom-emoji tab content) */}
      <div className="flex-1 overflow-y-auto px-2 py-2">
        {activeCategory === "custom" && customTab
          ? customTab.render(search)
          : (search.trim()
              ? filteredCategories
              : [CATEGORIES[typeof activeCategory === "number" ? activeCategory : 0]]
            ).map((cat) => (
              <div key={cat.label}>
                <p className="mb-1 px-1 text-[0.625rem] font-semibold uppercase tracking-wide text-foreground/45">
                  {cat.label}
                </p>
                <div className="grid grid-cols-8 gap-0.5">
                  {cat.emojis.map((emoji) => (
                    <button
                      key={emoji}
                      type="button"
                      onClick={() => handleSelect(emoji)}
                      className="rounded-md p-1 text-xl transition-transform hover:scale-125 hover:bg-foreground/10 active:scale-100"
                    >
                      {emoji}
                    </button>
                  ))}
                </div>
              </div>
            ))}
      </div>
    </>
  );

  if (embedded) {
    return <div className="flex h-full min-h-0 flex-col overflow-hidden">{content}</div>;
  }

  return createPortal(
    <div
      ref={panelRef}
      className="fixed z-[9999] flex h-[22rem] w-[21rem] max-w-[calc(100vw-1rem)] flex-col overflow-hidden rounded-xl border border-foreground/10 bg-[var(--card)] shadow-xl"
      style={{
        ...(pos.top != null ? { top: pos.top } : {}),
        ...(pos.bottom != null ? { bottom: pos.bottom } : {}),
        ...(pos.right != null ? { right: pos.right } : {}),
        ...(pos.left != null ? { left: pos.left } : {}),
        ...(pos.maxHeight != null ? { maxHeight: pos.maxHeight } : {}),
      }}
    >
      {content}
    </div>,
    document.body,
  );
}
