// ──────────────────────────────────────────────
// Default Configurations
// ──────────────────────────────────────────────
import type { GenerationParameters } from "../types/prompt.js";

/** Derived copy of the app version. Root package.json is canonical; this file is regenerated by pnpm version:sync. */
export const APP_VERSION = "2.4.4";

/** Stable synthetic connection id for the built-in local llama sidecar. */
export const LOCAL_SIDECAR_CONNECTION_ID = "__local_sidecar__";

/** Stable ID for the built-in Professor Mari assistant character. */
export const PROFESSOR_MARI_ID = "__professor_mari__";

/** Stable ID for the default OpenRouter free‑tier connection. */
export const DEFAULT_CONNECTION_ID = "__default_openrouter__";

/** Shared width for cached background thumbnails used by compact client surfaces. */
export const BACKGROUND_THUMBNAIL_WIDTH = 320;

/** Maximum length for image-backend instructions stored on an image connection. */
export const MAX_IMAGE_PROMPT_INSTRUCTIONS_LENGTH = 20_000;

/** Process-wide ceiling on concurrent media (image/video) provider requests.
 *  High enough that a single storyboard batch does not feel slower, low enough
 *  that a tile/sprite batch cannot stampede a local ComfyUI GPU or fan out
 *  unbounded calls against a paid provider (#5097). Overridable with the
 *  MARINARA_MEDIA_GENERATION_CONCURRENCY environment variable. */
export const DEFAULT_MEDIA_GENERATION_CONCURRENCY = 4;

export function normalizeImagePromptInstructions(value: unknown): string | null {
  if (typeof value !== "string") return null;
  const trimmed = value.trim().slice(0, MAX_IMAGE_PROMPT_INSTRUCTIONS_LENGTH);
  return trimmed || null;
}

/** Default system prompt for AI-backed translation. */
export const DEFAULT_TRANSLATION_SYSTEM_PROMPT =
  "You are a translator. Translate the given text accurately into {{targetLanguage}}, preserving formatting, markdown, and any special characters like *asterisks* for actions. Output ONLY the translated text, nothing else -- no explanations, no extra commentary.";

/** Resolve the documented language placeholder in a custom translation prompt. */
export function resolveTranslationSystemPrompt(prompt: string, targetLanguage: string): string {
  return prompt.replaceAll("{{targetLanguage}}", targetLanguage.trim());
}

/** Default generation parameters for new presets. */
export const DEFAULT_GENERATION_PARAMS: GenerationParameters = {
  temperature: 1,
  topP: 1,
  topK: 0,
  minP: 0,
  maxTokens: 4096,
  maxContext: 128000,
  frequencyPenalty: 0,
  presencePenalty: 0,
  reasoningEffort: "maximum",
  verbosity: null,
  serviceTier: null,
  assistantPrefill: "",
  assistantReasoningPrefill: "",
  customThinkingTags: [],
  customParameters: {},
  managedCustomParameters: {},
  squashSystemMessages: true,
  showThoughts: true,
  useMaxContext: false,
  stopSequences: [],
  strictRoleFormatting: true,
  singleUserMessage: false,
};

/** Maximum file sizes for uploads and imported assets. */
export const MAX_FILE_SIZES = {
  AVATAR: 10 * 1024 * 1024, // 10 MB
  CHARACTER_CARD: 32 * 1024 * 1024, // 32 MB
  BACKGROUND: 20 * 1024 * 1024, // 20 MB
  SPRITE: 10 * 1024 * 1024, // 10 MB
  CHARACTER_JSON: 5 * 1024 * 1024, // 5 MB
  LOREBOOK_JSON: 10 * 1024 * 1024, // 10 MB
  PRESET_JSON: 2 * 1024 * 1024, // 2 MB
  CHAT_JSONL: 50 * 1024 * 1024, // 50 MB
} as const;

/** Limits for various entities. */
export const LIMITS = {
  /** Max messages to include in context for agents */
  AGENT_CONTEXT_MESSAGES: 20,
  /** Legacy default for the previous global lorebook entry cap. Prefer LOREBOOK_ENTRY_LIMIT_* for new code. */
  MAX_LOREBOOK_ENTRIES: 100,
  /** Default max active entries a single lorebook may contribute per generation. */
  LOREBOOK_ENTRY_LIMIT_DEFAULT: 100,
  /** Minimum configurable active-entry limit for a lorebook. */
  LOREBOOK_ENTRY_LIMIT_MIN: 1,
  /** Maximum configurable active-entry limit for a lorebook. */
  LOREBOOK_ENTRY_LIMIT_MAX: 1000,
  /**
   * Default keyword-scan depth (messages back) for the per-turn lorebook scan
   * when neither the entry nor its lorebook sets one. An explicit per-entry or
   * per-lorebook scanDepth of 0 ("scan all") still scans the full history.
   */
  LOREBOOK_DEFAULT_SCAN_DEPTH: 10,
  /** Default global lorebook token budget per generation. 0 means unlimited when explicitly configured per chat. */
  DEFAULT_LOREBOOK_TOKEN_BUDGET: 8192,
  /**
   * Per-active-character lorebook token budget for a single Noodle refresh. Noodle can batch far
   * more characters into one generation call (up to 100, or uncapped with "All invited") than a
   * normal chat turn (1-2 characters), so it scales its own lorebook budget by active character
   * count instead of reusing DEFAULT_LOREBOOK_TOKEN_BUDGET outright — see NOODLE_LOREBOOK_TOKEN_BUDGET_FLOOR.
   */
  NOODLE_LOREBOOK_TOKEN_BUDGET_PER_ACCOUNT: 400,
  /** Minimum Noodle lorebook token budget even for a single active character. */
  NOODLE_LOREBOOK_TOKEN_BUDGET_FLOOR: 1500,
  /** Hard ceiling for all world/lore context activated by one Noodle refresh. */
  NOODLE_LOREBOOK_TOKEN_BUDGET_MAX: 8192,
  /** Default summary trigger: every N messages */
  SUMMARY_INTERVAL: 50,
  /** Default vectorization: top-K results */
  VECTOR_TOP_K: 10,
  /** Default recent-message window used to build lorebook vector queries. 0 means all messages. */
  LOREBOOK_VECTOR_QUERY_DEPTH_DEFAULT: 10,
  /** Maximum recent-message window for lorebook vector queries. */
  LOREBOOK_VECTOR_QUERY_DEPTH_MAX: 100,
  /** Default minimum cosine similarity for lorebook vector matches. */
  LOREBOOK_VECTOR_SCORE_THRESHOLD_DEFAULT: 0.3,
  /** Default maximum semantic/vector matches a single lorebook may contribute per generation. */
  LOREBOOK_VECTOR_MAX_RESULTS_DEFAULT: 10,
  /** Minimum maximum semantic/vector matches per lorebook. */
  LOREBOOK_VECTOR_MAX_RESULTS_MIN: 1,
  /** Maximum maximum semantic/vector matches per lorebook. */
  LOREBOOK_VECTOR_MAX_RESULTS_MAX: 100,
  /** Echo Chamber: messages per generation */
  ECHO_CHAMBER_MESSAGES: 5,
} as const;
