// This file is generated by packages/shared/scripts/generate-feature-registries.mjs.
// Add a new folder with engine.manifest.ts, then run pnpm --filter @marinara-engine/shared build.
import type { AnyTurnGameEngine } from "./engine.types.js";

import { unoGameEngine } from "./uno/engine.manifest.js";

export const TURN_GAME_ENGINES: readonly AnyTurnGameEngine[] = [
  unoGameEngine,
];

