// This file is generated by packages/shared/scripts/generate-feature-registries.mjs.
// Add a new folder with manifest.ts, then run pnpm --filter @marinara-engine/shared build.
import type { ToolDefinition } from "./tool-definitions.js";

import { rollDiceToolManifest } from "./tools/roll-dice/manifest.js";
import { updateGameStateToolManifest } from "./tools/update-game-state/manifest.js";
import { setExpressionToolManifest } from "./tools/set-expression/manifest.js";
import { triggerEventToolManifest } from "./tools/trigger-event/manifest.js";
import { searchLorebookToolManifest } from "./tools/search-lorebook/manifest.js";
import { saveLorebookEntryToolManifest } from "./tools/save-lorebook-entry/manifest.js";
import { readChatSummaryToolManifest } from "./tools/read-chat-summary/manifest.js";
import { appendChatSummaryToolManifest } from "./tools/append-chat-summary/manifest.js";
import { readChatVariableToolManifest } from "./tools/read-chat-variable/manifest.js";
import { writeChatVariableToolManifest } from "./tools/write-chat-variable/manifest.js";
import { spotifyGetCurrentPlaybackToolManifest } from "./tools/spotify-get-current-playback/manifest.js";
import { spotifyGetPlaylistsToolManifest } from "./tools/spotify-get-playlists/manifest.js";
import { spotifyGetPlaylistTracksToolManifest } from "./tools/spotify-get-playlist-tracks/manifest.js";
import { spotifySearchToolManifest } from "./tools/spotify-search/manifest.js";
import { spotifyPlayToolManifest } from "./tools/spotify-play/manifest.js";
import { spotifySetVolumeToolManifest } from "./tools/spotify-set-volume/manifest.js";
import { editChatMessageToolManifest } from "./tools/edit-chat-message/manifest.js";

export const BUILT_IN_TOOL_MANIFESTS: readonly ToolDefinition[] = [
  rollDiceToolManifest,
  updateGameStateToolManifest,
  setExpressionToolManifest,
  triggerEventToolManifest,
  searchLorebookToolManifest,
  saveLorebookEntryToolManifest,
  readChatSummaryToolManifest,
  appendChatSummaryToolManifest,
  readChatVariableToolManifest,
  writeChatVariableToolManifest,
  spotifyGetCurrentPlaybackToolManifest,
  spotifyGetPlaylistsToolManifest,
  spotifyGetPlaylistTracksToolManifest,
  spotifySearchToolManifest,
  spotifyPlayToolManifest,
  spotifySetVolumeToolManifest,
  editChatMessageToolManifest,
];

